pvc:
    name: pvc-wp
    storageClassName: nfs-client-wp
    accessModes:
        - ReadWriteOnce
    storage: 10Gi
deployment:
    name: wordpress
    replicaCount: 1
    imageName: wordpress:latest
    containerPort: 80
    dbHost: mysql-svc
    dbName: mysql
    dbUserKey: username
    dbPasswordKey: password
    uploadsMountPath: /var/www/html/wp-content/uploads
ingress:
    name: wp-ingress
    namespace: default
    issuer: letsencrypt
    className: nginx
    host: wordpress.152.42.150.3.nip.io
    tlsHost: wordpress.152.42.150.3.nip.io
    serviceName: wordpress-svc
    servicePort: 80
    certSecretName: wordpress-cert
service:
    name: wordpress-svc
    type: ClusterIP
    selector:
        app.kubernetes.io/name: wordpress
    port: 80
    targetPort: 80
secret:
    name: ENC[AES256_GCM,data:IxIT94+dJM6K+JRV0VuNpOtiNA==,iv:259BCphOK7JVXIzDVa8+D7ac22pAdUZQibonCvjcwL0=,tag:IVpPOwU4QjnbntykJu5Cvw==,type:str]
    username: ENC[AES256_GCM,data:TNtjHA==,iv:QJCsuPOibWtv8DTEx+uIMC1gjfU7lRmOamUiIzNNPAI=,tag:Sx3F3djj+US7Irw7W9zSKQ==,type:str]
    password: ENC[AES256_GCM,data:U8PbzpKwPNWxDA==,iv:CetKe9SgaMbuvulnDP553MM+rT6MCL2ztK0Jig/jUGM=,tag:56hi7hIDIv7g15bxSY6jBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-24T19:56:12Z"
    mac: ENC[AES256_GCM,data:IbU5ZazwOi8YuoZkqnKWVRsrRbPnFXGmSJHouE9e4wWOYIOuRvgY/XcjK03wmbErh/rH7K6c6+PKVGJF2nVodSieG0qMTnPOVyotaOtaQOWGSIeVAuVIyfsSQsdcB3XeGGjjpJSI9nbvSB5yxfwZ3diqxDlkbzUDmBqokd4LF+g=,iv:dfRCoTkidUmwJ4/ANVkFuIfr2mhRFRgam7auUOMrY20=,tag:ZN8TxEg0541bouK4asPaWQ==,type:str]
    pgp:
        - created_at: "2024-07-24T19:56:12Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAyuIySONH7uYAQv+JkmJGBye03nqTCi7ZyHNUnt4xBp7BLvz6fxiK2ndMG52
            iJB9AYuakKDuOIZOuES5kJnEqjeTFQV9pCvM+Kczl85Asafm34UjpD4OTxBtCi+i
            7h6FzNXm9FyDATvDaSXj7N3+f2bFOh2EU9ucM2p3T/keC5cpihGucXv5B/AwlBpe
            gEM2ZCgmkOqvRtABCcPYs69ASoOuKa3xf/iJCdXt3Afc82HR9LeVenUcnOAEHNTI
            KIV2WKK1GjKEEC9m6zW5HiWcCB3AWXBF23ymNO9rM6Z5ayr3nuzO36cbIWnGQVji
            HWa02bcK8GB8shfcrHcRiGVfL9+2OuEgDzjLV1oIs9gKDIbfldqt55FlZTM66ViO
            Y2ZVviwdv+aZbbTPvTs9ouLPpe4UUh/Z/+IVtR9/sX6/pSOvfZbDG7ww3Ox1cpk1
            kTZ6XU4QkA1/QAZ7A6yuTMviqzVObn06ZTqUKAilxCocNTV9RwHE5UcJFeenivyO
            TQEWzxrJQJBiiTOyy/UC0l4BZA9b2TcUDFBIJr3vlgLfIaskR5DRRdIbCja7sBlH
            kZ9urz4TuFne3Eo8AvSJ7qes8AVSxszTxJ2J4LKl2NSLgtwMZxFcxQVR/HZcI1f3
            PaoBP8guaROo+m6Wmpmg
            =xvXj
            -----END PGP MESSAGE-----
          fp: F9503BCE601534BDD7DE2E1EF22C71C81087F798
    encrypted_suffix: secret
    version: 3.9.0
