apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client-wp
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
  server: 206.189.107.43
  path: /opt/nfs/uploads
